language: python
python:
  - 3.4
  - 3.5
install:
  - pip install --upgrade setuptools
  - pip install flake8
  - pip install docutils
  - pip install coverage
  - pip install pygments
  - pip install git+https://github.com/KeepSafe/aiohttp.git
  - python setup.py develop

script:
  - flake8 sockjs
  - coverage run --source=sockjs setup.py test
  - coverage report
  - python setup.py check -rm
  - pip uninstall aiohttp -y && pip install aiohttp && python setup.py test
  - pip uninstall aiohttp -y && pip install aiohttp==0.18.3 && python setup.py test
